name: Compile Localization Files
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Compile Localization Files
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Localized file check-in by OneLocBuild Task')

    steps:
      - name: Checkout repo
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          token: ${{ secrets.AUTOMATION_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: 9.1.3
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Update source code
        run: npm run compile:loc

      - name: Commit changes
        uses: EndBug/add-and-commit@8c12ff729a98cfbcd3fe38b49f55eceb98a5ec02 # v7.5.0
        with:
          author_name: Loc Bot
          author_email: travisharris@microsoft.com
          message: 'Compiling Loc Files'
          add: '*.json'
