name: Deploy Standalone

on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
        with:
          submodules: true

      - name: Cache turbo build setup
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-docs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-docs-

      - name: Set up Node.js version 20.x
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: 20.x

      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: 9.1.3
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
              
      - run: pnpm turbo run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@4d27395796ac319302594769cfe812bd207490b1 # v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.STANDALONE_STATIC_WEB_APP }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          skip_app_build: true
          app_location: 'apps/Standalone/dist'
          output_location: 'apps/Standalone/dist'
